app_name = "fabric-shell"

styles_dir = "styles"
icons_dir = "icons"
artwork_cache_dir = "user_cache_dir-artworks"
# config_dir = "user_config_dir-fabric-shell"

spacing = 5
artwork_size = 120
no_artwork_icon_size = 40
icon_size = 24